language: node_js
node_js:
  - '6'
install:
  - npm install
script:
  - npm test
deploy:
  - provider: npm
    on:
      tags: true
      all_branches: true
    email: ${NPM_EMAIL}
    api_key: ${NPM_KEY}
